[Generale]
fqdn_sso="sso.example.org"
tld_sito="example.org"
domini_autorizzati=["example.org", "test.example.org"]
porta_http=":8080"
chiave_firma="secret"
cookie_sicuri=false
dummy_auth=true

[LDAP]
host="ldap.example.org"
porta="389"
