[Generale]
fqdn_sso="localhost"
tld_sito="localhost"
domini_autorizzati=["example.org", "test.example.org"]
porta_http=":8080"
chiave_firma="secret"
cookie_sicuri=false
titolo_pagina="SSO Login"
dummy_auth=false

[LDAP]
host="localhost"
porta="389"
utente="admin"
password="GoodNewsEveryone"
base_dn="dc=planetexpress,dc=com"

[Limiti]
rps_totali=16.6
max_richieste=5000
