[Generale]
fqdn_sso="sso.example.org"
tld_sito="example.org"
domini_autorizzati=["example.org", "test.example.org"]
porta_http=":5473"
chiave_firma="secret"
cookie_sicuri=false
titolo_pagina="SSO Login"
dummy_auth=false

[LDAP]
host="ldap.example.org"
porta="389"
utente="admin"
password="admin"
base_dn="dc=example,dc=org"
